name: deploy-pages
on: push

env:
  GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Build & Test Node
      run: |-
        npm ci
        npm run lint
        npm run deploy:storybook -- --ci